### ISSUE TITLE
Cannot add Lemon Milk font

### ISSUE THREAD

**Issue by szmarczak** [WilliamRagstad/Font-Manager#16]
Nothing just happens if I drag and drop the `LemonMilkbold.otf` file into the window.

https://www.dafont.com/lemon-milk.font

**Comment by szmarczak** [comment]
As you can see, if I click "yes" on the overwrite the font list just freezes and I cannot select anything.

![3](https://user-images.githubusercontent.com/36894700/71516324-8e957e00-28a8-11ea-893a-1b6a52643b37.gif)

**Comment by szmarczak** [comment]
If I add it from the list nothing happens either:

![3](https://user-images.githubusercontent.com/36894700/71516353-cdc3cf00-28a8-11ea-941e-3011ac92c296.gif)

**Comment by MoneyAllDay** [comment]
> 
> 
> ![3](https://user-images.githubusercontent.com/36894700/71516324-8e957e00-28a8-11ea-893a-1b6a52643b37.gif)



> 
> 
> ![3](https://user-images.githubusercontent.com/36894700/71516353-cdc3cf00-28a8-11ea-941e-3011ac92c296.gif)

I'm sorry to be bumping this as off topic but which software did you use to capture those gifs? Quite good size for the quality.

**Comment by szmarczak** [comment]
@MoneyAllDay Sure, I used [LICEcap](https://www.cockos.com/licecap/). It gives me 20-30 FPS when I record as GIF, haven't tried the LCF format.

**Comment by WilliamRagstad** [comment]
Yes, this was an issue due to its name. As you could see, the font was called _Lemon/Milk_ which caused a problem when generating the folder structure for that particular font because the name was not sanitized correctly. Basically, the '/' made my program think that Milk was a sub-directory to Lemon... This is now fixed in the next release.
