### ISSUE TITLE
Problems with VirusTotal

### ISSUE THREAD

**Issue by richtigersohn** [WilliamRagstad/Font-Manager#45]
I wanted to use this font changer, to of course change my fonts. I downloaded the .exe file and put it through VirusTotal, because I do that with every file I download. But when I analyzed the latest release, I got a warning for " Trojan.Win32.Save.a". Just wanted to know if that has something to do with the fact that it changes local files or whatever. 
![Screenshot 2021-03-08 173603](https://user-images.githubusercontent.com/80275760/110351122-c8c5e800-8034-11eb-9373-0ea6663271ed.png)

**Comment by WilliamRagstad** [comment]
It might have picked up that Font Manager writes to files and labeled it as malicious for that reason, I can't come up with another explanation. I can ensure you that the program is safe and only modify files in a single folder. The source code is open and free for inspection and is used by thousands of people. I hope you have gotten a legitimate version from this GitHub, otherwise you have rights to be worried.
